#!/bin/bash

# check if PYCODE is set
if [ -z "$PYCODE" ]; then
	echo "Error: PYCODE variable is not set."
	exit 1
fi

# create a temporary variable
TEMP_FILE=$(mktemp)

# update temporary variable
echo $PYCODE >"$TEMP_FILE"

# output value
python3 $TEMP_FILE

rm $TEMP_FILE
